class ResearchOptions {
  static const List<String> interests = [
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Medical Imaging",
    "Brain Tumor Segmentation",
    "Healthcare AI",
    "Bioinformatics",
    "Robotics",
    "Data Science",
    "Cybersecurity",
    "Human-Computer Interaction",
    "Software Engineering",
    "Cloud Computing",
    "IoT",
    "Federated Learning",
    "Explainable AI",
    "Remote Sensing",
    "Recommender Systems",
  ];

  static const List<String> skills = [
    "Flutter",
    "Dart",
    "Python",
    "Java",
    "C++",
    "Machine Learning",
    "Deep Learning",
    "PyTorch",
    "TensorFlow",
    "OpenCV",
    "Data Analysis",
    "Research Writing",
    "Paper Review",
    "Experiment Design",
    "GitHub",
    "Firebase",
    "FastAPI",
    "SQL",
    "LaTeX",
    "UI/UX Design",
  ];
}
